honeybrid: connections.h File Reference
connections.h File Reference
Functions
status_t switch_state (struct conn_struct *conn, int new_state)
status_t init_pkt (unsigned char *nf_packet, struct pkt_struct **pk, u_int32_t mark)
init the current packet structure with meta-information such as the origin and the number of bytes of data
void free_pkt (struct pkt_struct *pkt)
free the current packet structure
status_t store_pkt (struct conn_struct *conn, struct pkt_struct *pkt)
Store the current packet as part of the connection to replay it later.
status_t init_conn (struct pkt_struct *pkt, struct conn_struct **conn)
init the current context using the tuples
status_t expire_conn (gpointer key, struct conn_struct *cur_conn, gint *expiration_delay)
called for each entry in the B-Tree, if a time value is upper to "expiration_delay" (default is 120 sec) and the connection is not marked as redirected, entry is deleted
void free_conn (gpointer key, gpointer trash)
called for each entry in the pointer array, each entry is a key that is deleted from the B-Tree
status_t init_mark (struct pkt_struct *pkt, const struct conn_struct *conn)
void clean ()
watchman for the b_tree, wake up every minute and check every entries
status_t setup_redirection (struct conn_struct *conn, uint32_t hih_id)
called for each connection being redirected to setup and start the redirection process
Function Documentation
void clean ()
watchman for the b_tree, wake up every minute and check every entries
clean
init the table
call the clean function for each value
remove each key listed from the btree
free the array
References conn_tree, conntreelock, entrytoclean, expire_conn(), free_conn(), H, ICONFIG, OK, threading, threading_cond, and threading_cond_lock.
Referenced by switch_clean().
status_t expire_conn (gpointer key, struct conn_struct * conn, gint * expiration_delay)
called for each entry in the B-Tree, if a time value is upper to "expiration_delay" (default is 120 sec) and the connection is not marked as redirected, entry is deleted
expire_conn
Parameters
[in] key,a pointer to the current B-Tree key value
[in] conn,a pointer to the current B-Tree associated value
[in] expiration_delay
Returns
FALSE, to continue to traverse the tree (if TRUE is returned, traversal is stopped)
output final statistics about the connection
lock the structure, this will never be unlocked
list the entry for later removal
References conn_struct::access_time, connection_log(), entrytoclean, H, INIT, conn_struct::lock, and conn_struct::state.
Referenced by clean(), and close_conn_tree().
void free_conn (gpointer key, gpointer trash)
called for each entry in the pointer array, each entry is a key that is deleted from the B-Tree
free_conn
Parameters
[in] key,a pointer to the current B-Tree key value stored in the pointer table
[in] trash,user data, unused
References conn_struct::BUFFER, conn, conn_tree, conntreelock, conn_struct::decision_rule, free_pkt(), H, conn_struct::hih, conn_struct::key, conn_struct::key_ext, conn_struct::key_lih, conn_struct::lock, hih_struct::redirect_key, and conn_struct::start_timestamp.
Referenced by clean(), and close_conn_tree().
void free_pkt (struct pkt_struct * pkt)
free the current packet structure
free_pkt
Parameters
[in] pkt,: struct pkt_struct to free
References packet::FRAME, packet::ip, pkt_struct::key, pkt_struct::key_dst, pkt_struct::key_src, and pkt_struct::packet.
Referenced by free_conn(), and process_packet().
status_t init_conn (struct pkt_struct * pkt, struct conn_struct ** conn)
init the current context using the tuples
init_conn
Parameters
[in] pkt,: struct pkt_struct to work with
[in] conn,: struct conn_struct to work with
Returns
0 if success, anything else otherwise
Get current time to update or create the structure
References conn_lookup(), create_conn(), NOK, OK, and update_conn().
Referenced by process_packet().
status_t init_mark (struct pkt_struct * pkt, const struct conn_struct * conn)
References conn_struct::downlink_mark, EXT, HIH, LIH, pkt_struct::mark, NOK, OK, pkt_struct::origin, and conn_struct::uplink_mark.
Referenced by process_packet().
status_t init_pkt (unsigned char * nf_packet, struct pkt_struct ** pkt_in, u_int32_t mark)
init the current packet structure with meta-information such as the origin and the number of bytes of data
init_pkt
Parameters
[in] nf_packet,: The raw packet from the queue
[in] pkt,: The packet metadata structure for this packet
[in] mark,: Netfilter mark of the packet
Returns
the origin of the packet
Create fake ethernet header (used later by bpf_filter)
The most important part is to give to this ethernet header the type "IP protocol"
Add the packet IP header and payload to the packet structure
Process TCP packets
key_src is the tuple with the source information {Source IP}:{Source Port}
key_dst is the one with the destination information {Dest IP}:{Dest Port}
Process UDP packet
key_src
key_dst
Every other packets are ignored
References pkt_struct::data, pkt_struct::DE, ETHER_HDR_LEN, EXT, packet::FRAME, H, packet::ip, pkt_struct::key, pkt_struct::key_dst, pkt_struct::key_src, pkt_struct::mark, mark, NOK, OK, pkt_struct::origin, pkt_struct::packet, packet::payload, pkt_struct::position, pkt_struct::size, TCP, packet::tcp, UDP, and packet::udp.
Referenced by process_packet().
status_t setup_redirection (struct conn_struct * conn, uint32_t hih_use)
called for each connection being redirected to setup and start the redirection process
setup_redirection
Parameters
[in] conn,: redirected connection metadata
Returns
OK when done, NOK in case of failure
we check for concurrent connections using the same HIH_IP:PORT <-> EXT_IP
We then update the status of the connection structure
We reset the LIH
We replay the first packets
References hih_struct::addr, addr2int(), target::back_handlers, conn_struct::BUFFER, DECISION, define_expected_data(), EXT, FORWARD, forward(), H, high_redirection_table, conn_struct::hih, hih_struct::hihID, hihredirlock, conn_struct::id, backend::iface, hih_struct::iface, interface::ip, conn_struct::key, conn_struct::key_ext, conn_struct::key_lih, hih_struct::lih_addr, NOK, OK, pkt_struct::origin, hih_struct::port, hih_struct::redirect_key, REPLAY, conn_struct::replay_id, reset_lih(), conn_struct::stat_time, switch_state(), conn_struct::target, and conn_struct::uplink_mark.
Referenced by DE_process_packet().
status_t store_pkt (struct conn_struct * conn, struct pkt_struct * pkt)
Store the current packet as part of the connection to replay it later.
store_pkt function
Parameters
[in] pkt,: struct pkt_struct to work with
[in] conn,: struct conn_struct to work with
Returns
the position of the packet in the list in case of success, a negative value if storage has failed
Lock the structure
Append pkt to the singly-linked list of conn
Get the packet position
Unlock the structure
References conn_struct::BUFFER, H, conn_struct::id, conn_struct::key, conn_struct::lock, NOK, OK, and pkt_struct::position.
Referenced by process_packet().
status_t switch_state (struct conn_struct * conn, int new_state)
References H, conn_struct::id, lookup_state(), OK, and conn_struct::state.
Referenced by DE_process_packet(), process_packet(), replay(), and setup_redirection().