honeybrid: constants.c File Reference
constants.c File Reference
#include "types.h"
Functions
const char * lookup_proto (protocol_t proto)
const char * lookup_origin (origin_t origin)
const char * lookup_state (conn_status_t state)
Variables
const char * protocol_string [__MAX_PROTOCOL]
const char * packet_origin_string [__MAX_ORIGIN]
const char * conn_status_string [__MAX_CONN_STATUS]
Function Documentation
const char* lookup_origin (origin_t origin)
References origin, and packet_origin_string.
Referenced by process_packet().
const char* lookup_proto (protocol_t proto)
References proto, and protocol_string.
Referenced by process_packet().
const char* lookup_state (conn_status_t state)
References conn_status_string, and state.
Referenced by process_packet(), and switch_state().
Variable Documentation
const char* conn_status_string[__MAX_CONN_STATUS]
Initial value:
 {
        [0 ... __MAX_CONN_STATUS-1] = "UNKNOWN",
        [INIT]          = "INIT",
        [DECISION]      = "DECISION",
        [REPLAY]        = "REPLAY",
        [FORWARD]       = "FORWARD",
        [PROXY]         = "PROXY",
        [DROP]          = "DROP",
        [CONTROL]       = "CONTROL"
}
Referenced by lookup_state().
const char* packet_origin_string[__MAX_ORIGIN]
Initial value:
 {
        [0 ... __MAX_ORIGIN-1] = "UNKNOWN",
        [EXT] = "[EXT] External",
        [LIH] = "[LIH] Low-interaction honeypot",
        [HIH] = "[HIH] High-interaction honeypot"
}
Referenced by lookup_origin().
const char* protocol_string[__MAX_PROTOCOL]
Initial value:
 {
        [0 ... __MAX_PROTOCOL-1] = "INVALID",
        [ICMP] = "ICMP",
        [IGMP] = "IGMP",
        [TCP] = "TCP",
        [UDP] = "UDP",
        [GRE] = "GRE"
}
Referenced by lookup_proto().