honeybrid: decision_engine.c File Reference
decision_engine.c File Reference
Decision Engine for honeybrid.
#include <malloc.h>
#include <string.h>
#include <glib.h>
#include "decision_engine.h"
#include "netcode.h"
#include "modules.h"
#include "tables.h"
#include "log.h"
Functions
struct node * DE_build_subtree (const gchar *expr)
recursively process the expression and creates the nodes
void * DE_create_tree (const gchar *equation)
build a boolean decision tree for a given equation
int decide (struct pkt_struct *pkt)
decide upon a given paken if the connection is to be redirected or not
int DE_process_packet (struct pkt_struct *pkt)
submit packets for decision using decision rules and decision modules
void DE_submit_packet ()
handle connections being decided and submits packets for decision
void DE_push_pkt (struct pkt_struct *pkt)
push packet to the DE_submit_pkt queue (equivalent of DE_submit_packet() but without using a thread)
Detailed Description
Decision Engine for honeybrid.
This engine creates boolean decision trees from a rule list and process incoming connection using those trees. If the tree return TRUE, the redirected value of the connection is set to 1.
Author:
Julien Vehent, 2007
Thomas Coquelin, 2008
Function Documentation
struct node* DE_build_subtree (const gchar * expr) [read]
recursively process the expression and creates the nodes
build_subtree
Parameters:
[in] expr,a part of the boolean equation
TODO: to be freed when destroying DE_rules
test presence of AND operator
composed expression: separate the left part
split on "AND" operator
process left part of the AND
call function with right side of expr
single module in expression, just add the leaf
get module structure from DE_mod
return pointer to this leaf
References node::arg, errx(), node::false, node::function, module, node::module, node::module_name, and node::true.
Referenced by DE_create_tree().
void* DE_create_tree (const gchar * equation)
build a boolean decision tree for a given equation
DE_create_tree
Parameters:
[in] equation a boolean equation
Returns:
tree_root a pointer to the root of the boolean decision tree
create a glib table to store the equation
first subgroup
store address of the root
for all the other subgroups
get the pointer to the beginning of the new subtree
connect new subtree to the previous one subtree (n) is a son of subtree(n-1)
and go to the next one
in subtree (n-1), each FALSE branch is connected to the head of subtree(n)
this subtree is done, so n become n-1
References DE_build_subtree(), node::false, and node::true.
Referenced by yyparse().
int DE_process_packet (struct pkt_struct * pkt)
submit packets for decision using decision rules and decision modules
DE_process_packet
default is to return "drop" to the QUEUE
we update the state
we release the packet
no backend defined, so we simply forward the packets to its destination
backend defined, so we'll use the backend_rule for the next packet
we leave the state unmodified (the rule probably needs more material to decide), and we release the packet
References target::back_rule, pkt_struct::conn, CONTROL, target::control_rule, DE_ACCEPT, DE_NO_RULE, DE_REJECT, DE_UNKNOWN, decide(), DECISION, conn_struct::decision_packet_id, DROP, target::front_rule, H, conn_struct::id, INIT, conn_struct::key, OK, PROXY, setup_redirection(), conn_struct::state, switch_state(), conn_struct::target, and conn_struct::total_packet.
Referenced by DE_submit_packet().
void DE_push_pkt (struct pkt_struct * pkt)
push packet to the DE_submit_pkt queue (equivalent of DE_submit_packet() but without using a thread)
DE_push_pkt DEPRECATED,
Todo:
to remove
Parameters:
[in] pkt,: packet to push
Returns:
OK
References pkt_struct::conn, DE_queue, DE_queue_lock, H, and conn_struct::id.
void DE_submit_packet ()
handle connections being decided and submits packets for decision
DE_submit_packet DEPRECATED,
Todo:
to remove
Now that this entry was processed, we can remove it from the DE queue
References DE_process_packet(), DE_queue, DE_queue_lock, OK, and threading.
Referenced by main().
int decide (struct pkt_struct * pkt)
decide upon a given paken if the connection is to be redirected or not
decide
Parameters:
[in] pkt,: packet used to decide
Returns:
decision
globalresult is used to store the final result of the boolean equation of module 3 possible outcome: "-1" means "can't decide, needs more data to decide" "0" means "reject" "1" means "accept"
start processing the tree from the root
node->result is used to store the outcome of an individual module
node->info_result is used to store additional information about the decision
call module
if result is true, forward to true node or exit with 1
update decision_rule information
go to next node
end of the tree, exit
end of the tree, exit
result is false (result == 0), forward to false node or exit with 0
go to the next subgroup
end of the tree, exit
References pkt_struct::conn, conn_struct::decision_rule, H, conn_struct::id, mod_args::node, mod_args::pkt, and run_module().
Referenced by DE_process_packet().