honeybrid: decision_engine.h File Reference
decision_engine.h File Reference
#include <glib.h>
#include "tables.h"
Data Structures
struct tree
Defines
#define DE_NO_RULE -2
#define DE_UNKNOWN -1
#define DE_REJECT 0
#define DE_ACCEPT 1
Functions
void * DE_create_tree (const gchar *equation)
build a boolean decision tree for a given equation
void DE_submit_packet ()
handle connections being decided and submits packets for decision
void DE_push_pkt (struct pkt_struct *pkt)
push packet to the DE_submit_pkt queue (equivalent of DE_submit_packet() but without using a thread)
int DE_process_packet (struct pkt_struct *pkt)
submit packets for decision using decision rules and decision modules
Variables
GHashTable * DE_rules
struct tree tree
GStaticRWLock DE_queue_lock
GSList * DE_queue
Define Documentation
#define DE_ACCEPT 1
Referenced by DE_process_packet().
#define DE_NO_RULE -2
Referenced by DE_process_packet().
#define DE_REJECT 0
Referenced by DE_process_packet().
#define DE_UNKNOWN -1
Referenced by DE_process_packet().
Function Documentation
void* DE_create_tree (const gchar * equation)
build a boolean decision tree for a given equation
DE_create_tree
Parameters:
[in] equation a boolean equation
Returns:
tree_root a pointer to the root of the boolean decision tree
create a glib table to store the equation
first subgroup
store address of the root
for all the other subgroups
get the pointer to the beginning of the new subtree
connect new subtree to the previous one subtree (n) is a son of subtree(n-1)
and go to the next one
in subtree (n-1), each FALSE branch is connected to the head of subtree(n)
this subtree is done, so n become n-1
References DE_build_subtree(), node::false, and node::true.
Referenced by yyparse().
int DE_process_packet (struct pkt_struct * pkt)
submit packets for decision using decision rules and decision modules
DE_process_packet
default is to return "drop" to the QUEUE
we update the state
we release the packet
no backend defined, so we simply forward the packets to its destination
backend defined, so we'll use the backend_rule for the next packet
we leave the state unmodified (the rule probably needs more material to decide), and we release the packet
References target::back_rule, pkt_struct::conn, CONTROL, target::control_rule, DE_ACCEPT, DE_NO_RULE, DE_REJECT, DE_UNKNOWN, decide(), DECISION, conn_struct::decision_packet_id, DROP, target::front_rule, H, conn_struct::id, INIT, conn_struct::key, OK, PROXY, setup_redirection(), conn_struct::state, switch_state(), conn_struct::target, and conn_struct::total_packet.
Referenced by DE_submit_packet().
void DE_push_pkt (struct pkt_struct * pkt)
push packet to the DE_submit_pkt queue (equivalent of DE_submit_packet() but without using a thread)
DE_push_pkt DEPRECATED,
Todo:
to remove
Parameters:
[in] pkt,: packet to push
Returns:
OK
References pkt_struct::conn, DE_queue, DE_queue_lock, H, and conn_struct::id.
void DE_submit_packet ()
handle connections being decided and submits packets for decision
DE_submit_packet DEPRECATED,
Todo:
to remove
Now that this entry was processed, we can remove it from the DE queue
References DE_process_packet(), DE_queue, DE_queue_lock, OK, and threading.
Referenced by main().
Variable Documentation
GSList* DE_queue
Referenced by DE_push_pkt(), DE_submit_packet(), and init_variables().
GStaticRWLock DE_queue_lock
Referenced by DE_push_pkt(), DE_submit_packet(), and init_variables().
GHashTable* DE_rules
Referenced by close_hash(), and init_variables().
struct tree tree