honeybrid: err.c File Reference
err.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <errno.h>
Functions
void err (int eval, const char *fmt,...)
void warn (const char *fmt,...)
void errx (int eval, const char *fmt,...)
void warnx (const char *fmt,...)
Function Documentation
void err (int eval, const char * fmt, ...)
Referenced by init_parser(), main(), open_connection_log(), and open_debug_log().
void errx (int eval, const char * fmt, ...)
Referenced by config_lookup(), DE_build_subtree(), get_module(), init_modules(), init_signal(), init_variables(), main(), netlink_loop(), open_connection_log(), open_debug_log(), and yyparse().
void warn (const char * fmt, ...)
void warnx (const char * fmt, ...)
Referenced by open_connection_log(), and open_debug_log().