honeybrid: honeybrid.h File Reference
honeybrid.h File Reference
#include <pcap.h>
Defines
#define VERSION "1.0"
#define PIDFILE "/var/run/honeybrid.pid"
#define G_STATIC_RW_LOCK_INIT { G_STATIC_MUTEX_INIT, NULL, NULL, 0, FALSE, 0, 0 }
#define G_THREADS_ENABLED
#define DESTSIZE 15
#define CONF_MAX_LINE 1024
#define RESET_HIH 0
#define BUFSIZE 2048
#define PAYLOADSIZE 0xffff
Functions
int daemon (int, int)
int yyparse (void)
Variables
FILE * yyin = (FILE *) 0
int running
GThread * thread_clean
GThread * thread_de
Define Documentation
#define BUFSIZE 2048
use by NF_QUEUE to set the data size of received packets
Referenced by netlink_loop().
#define CONF_MAX_LINE 1024
max size of a line in the configuration file
#define DESTSIZE 15
Decision Engine thread enabled
Two strategies: with thread or with libev If USE_LIBEV is defined, the program loops on the main libev loop:
packets on queue are processed through libev callback
connection structures are cleaned by libev timer If not, then the program loops on nfqueue:
packets on queue are processed through nfqueue callback
connection structures are cleaned by a thread
max size of an IP address (4*3 = 12 + 3 dots = 15)
#define G_STATIC_RW_LOCK_INIT { G_STATIC_MUTEX_INIT, NULL, NULL, 0, FALSE, 0, 0 }
writing lock initialization
#define G_THREADS_ENABLED
Multi-thread safe mode
#define PAYLOADSIZE 0xffff
use by NF_QUEUE to set the data size of received packets
Referenced by netlink_loop().
#define PIDFILE "/var/run/honeybrid.pid"
File to store PID
Referenced by close_all(), and main().
#define RESET_HIH 0
use to reset (1) or accept (0) connections initiated by HIH
#define VERSION "1.0"
Version (should always be in sync with the content of the VERSION file)
Referenced by main(), and usage().
Function Documentation
int daemon (int , int)
Referenced by main().
int yyparse (void)
We store a pointer to GKeyFile object in the module hash table
We then check if the file exists. Otherwise we create it
If the file exists, we try to load it into memory
Todo:
free all these structures, and close file descriptor when exiting
We store a pointer to the module function in the module hash table If the module function isn't defined in get_module(), the application will exit and display an error message
We store a pointer to the module function in the module hash table If the module function isn't defined in get_module(), the application will exit and display an error message
References YYSTYPE::addr, config, DE_create_tree(), errx(), get_module(), YYSTYPE::gstring, YYSTYPE::hash, LINKTYPE, module, YYSTYPE::number, YYSTYPE::string, YYSTYPE::target, targets, YY_, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, YYDPRINTF, YYEMPTY, YYEOF, YYFINAL, YYID, YYINITDEPTH, YYLAST, YYLEX, YYMAXDEPTH, YYNTOKENS, YYPACT_NINF, YYPOPSTACK, YYSIZE_T, YYSTACK_ALLOC, YYSTACK_ALLOC_MAXIMUM, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, YYTABLE_NINF, YYTERROR, and YYTRANSLATE.
Referenced by init_parser().
Variable Documentation
int running
Referenced by init_variables(), netlink_loop(), and term_signal_handler().
GThread* thread_clean
Referenced by close_thread(), and main().
GThread* thread_de
Referenced by close_thread(), and main().
FILE * yyin = (FILE *) 0
Referenced by init_parser(), yyget_in(), and yyset_in().