honeybrid: honeybrid.c File Reference
honeybrid.c File Reference
Main File.
#include <sys/param.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <string.h>
#include <err.h>
#include <errno.h>
#include <syslog.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <signal.h>
#include <malloc.h>
#include <netinet/in.h>
#include <linux/netfilter.h>
#include <libnetfilter_queue/libnetfilter_queue.h>
#include <arpa/inet.h>
#include <glib.h>
#include <execinfo.h>
#include <ev.h>
#include "tables.h"
#include "honeybrid.h"
#include "netcode.h"
#include "log.h"
#include "decision_engine.h"
#include "modules.h"
Functions
void usage (char **argv)
include "pcap_tool.h"
void print_trace (void)
Obtain a backtrace and print it to stdout.
int close_thread ()
Function that waits for thread to close themselves.
int free_table (gchar *key, gchar *value, gpointer data)
Function to free memory in the different table created.
int free_hash (gchar *key, GHashTable *value, gpointer data)
Function to free memory in the different subhash created.
int close_hash ()
Destroy the different hashes used by honeybrid.
int close_conn_tree ()
Function to free memory taken by conn_tree.
void free_target (struct target *t, gpointer user_data)
int close_target (void)
destroy global structure "targets" when the program has to quit
void close_all (void)
destroy structures and free memory when the program has to quit
int term_signal_handler (int signal_nb, siginfo_t *siginfo, void *context)
called when the program receive a signal that should close the program, free memory and delete lock file
void switch_clean ()
call the packet cleaner
void init_parser (char *filename)
Configuration parsing function, read the configuration from a specific file and parse it into a hash table or other tree data structures using Bison/Flex.
void init_variables ()
short int netlink_loop (unsigned short int queuenum)
Function to create and maintain the NF_QUEUE loop.
void init_signal ()
installs signal handlers
int main (int argc, char *argv[])
process arguments, daemonize, init variables, create QUEUE handler and process each packet
Detailed Description
Main File.
This is the main program file for Honeybrid. It creates a hook using LibNetfilter Queue and, for each connection, maintain a stateful table. It forward a packet to a determined destination and submit this packet to the decision engine. When the decision engine decide to redirect a connection, this redirection engine replay the recorded connection to its new destination and maintain it until its end.
Packets needs to be redirected to the QUEUE destination using netfilter, this can be done using: # iptables -A INPUT -j QUEUE && iptables -A FORWARD -j QUEUE && iptables -A OUTPUT -j QUEUE
filters can also be set up using the regulars iptables capabilities, it is also recommended to limit the redirections to TCP and UDP packets (just add the option -p to the iptables commands)
Dependencies:
linux kernel >= 2.6.18 & <=2.6.23
libnetfilter-queue-dev & libnetfilter-queue1
libnfnetlink >= 0.0.25
libglib2.0-dev & libglib2.0-0
Known problem: If the buffer size under linux is too low, the IPQ subsystem will exit with the error "Failed to received netlink message: No buffer space available" To avoid that, increase the buffer value in /proc/sys/net/core/rmem_default (and rmem_max)
J. Vehent, 2007 Thomas Coquelin, 2008 Robin Berthier, 2007-2009
Function Documentation
void close_all (void)
destroy structures and free memory when the program has to quit
close_all
delete lock file (only if the process ran as a daemon)
wait for thread to close
delete hashes
delete conn_tree
References close_conn_tree(), close_hash(), close_target(), close_thread(), ICONFIG, and PIDFILE.
Referenced by main().
int close_conn_tree ()
Function to free memory taken by conn_tree.
close_conn_tree function
clean the memory traverse the B-Tree to remove the singly linked lists and then destroy the B-Tree
call the clean function for each value, delete the value if TRUE is returned
remove each key listed from the btree
free the array
close log file
References close_connection_log(), conn_tree, entrytoclean, expire_conn(), and free_conn().
Referenced by close_all().
int close_hash ()
Destroy the different hashes used by honeybrid.
close_hash function
Destroy hash tables
this table generates invalid free error in valgrind
and also a seg fault... g_print("close_hash():\tDestroying table DE_rules\n"); g_hash_table_foreach_remove(DE_rules, (GHRFunc) free_table, NULL); g_hash_table_destroy(DE_rules);
References config, DE_rules, free_table(), high_redirection_table, and log_table.
Referenced by close_all().
int close_target (void)
destroy global structure "targets" when the program has to quit
close_target
References free_target(), OK, and targets.
Referenced by close_all().
int close_thread ()
Function that waits for thread to close themselves.
close_thread
References NOK, thread_clean, thread_de, and threading.
Referenced by close_all().
int free_hash (gchar * key, GHashTable * value, gpointer data)
Function to free memory in the different subhash created.
free_hash
References free_table().
int free_table (gchar * key, gchar * value, gpointer data)
Function to free memory in the different table created.
free_table
Referenced by close_hash(), and free_hash().
void free_target (struct target * t, gpointer user_data)
References target::back_handler, target::back_rule, target::control_rule, target::filter, target::front_handler, and target::front_rule.
Referenced by close_target().
void init_parser (char * filename)
Configuration parsing function, read the configuration from a specific file and parse it into a hash table or other tree data structures using Bison/Flex.
parse_config
References err(), yyin, and yyparse().
Referenced by main().
void init_signal ()
installs signal handlers
init_signal
Returns:
0 if exit with success, anything else if not
Install terminating signal handler:
SIGHUP
SIGINT
SIGQUIT
SIGILL
SIGSEGV
SIGTERM
SIGBUS
ignore signals:
SIGABRT
SIGALRM
SIGUSR2
SIGPOLL
rotate logs:
SIGUSR1
References errx(), rotate_connection_log(), and term_signal_handler().
Referenced by main().
void init_variables ()
create the hash table to store the config
create the array of pointer to store the target information
create the hash table to store module information
create the hash table for the log engine
create the hash table for the redirection table
Todo:
DEPRECATED if (NULL == (low_redirection_table = g_hash_table_new(g_str_hash, g_str_equal))) errx(1,"%s: Fatal error while creating redirection_table hash table.\n", __func__);
create the hash table for the LIH list
Todo:
DEPRECATED if (NULL == (low_honeypot_addr = g_hash_table_new(g_int_hash, g_int_equal))) errx(1,"%s: Fatal error while creating low_honeypot_addr hash table.\n", __func__);
create the hash table for the HIH list
Todo:
DEPRECATED if (NULL == (high_honeypot_addr = g_hash_table_new(g_int_hash, g_int_equal))) errx(1, "%s: Error while creating high_honeypot_addr hash table.\n", __func__);
create the hash table to store the pointers to the boolean execution trees
init the log singly linked list
init the connection id counter
Enable data processing
init the security locks
g_tree_new_full - create the main B-Tree to store meta informations of active connections
Parameters:
[in] GCompareDataFunc,: function to compare 2 entries, we use strcmp
[in] GDestroyNotify,: function called to destroy a key
[in] GDestroyNotify,: function called to destroy a value
Returns:
a new GTree.
References c_id, config, conn_tree, DE_queue, DE_queue_lock, DE_rules, errx(), log_list, log_table, module, OK, running, rwlock, and targets.
Referenced by main().
int main (int argc, char * argv[])
process arguments, daemonize, init variables, create QUEUE handler and process each packet
main
Parameters:
[in] argc,number of arguments
[in] argv,table with arguments
Returns:
0 if exit with success, anything else if not
parsing arguments
define configuration filename
send a shutdown request to honeybrid
convert argument to int
check that processus exists
send signal USR1 to PID
Todo:
add a signal handler to output statistics (figure out the correct file description for output...) Statistics should include:
version
start time and duration
packet processed: total TCP UDP Other
connection processed: total INIT DECISION REPLAY FORWARD INVALID PROXY
decision engine, for each module: rules loaded signature loaded connection redirected (MATCH) connection left alone (DOES NOT MATCH)
errors NF_QUEUE restarts expected data
top ports?
top IP addresses?
init glib thread system
Todo:
check if threads are correctly freed
initialize signal handlers
initialize syslog
initialize data structures
parse the configuration files and store values in memory
Create PID file, we might not be able to remove it
reopening file descriptor now that we're a daemon
initiate outgoing connection control => no longer needed init_control();
initiate decision engine modules => done automatically in rules.y, except for init_mod_hash:
create the two raw sockets for UDP/IP and TCP/IP
create a thread for the management, cleaning stuffs and so on
Starting the nfqueue loop to start processing packets
sometimes netlink_loop exits by itself... so we have to restart it int i = 0; while (running == OK) { netlink_loop(queuenum); g_printerr("%s Netlink loop exited (%d times so far)\n", H(0), i); g_usleep(1000000); i++; if (i>100) { g_printerr("%s Reached maximum of 100 restarts... giving up\n", H(0)); running = NOK; } }
References close_all(), daemon(), DE_submit_packet(), err(), errx(), H, ICONFIG, init_modules(), init_parser(), init_raw_sockets(), init_signal(), init_variables(), mainpid, netlink_loop(), OK, open_connection_log(), open_debug_log(), PIDFILE, switch_clean(), tcp_rsd, thread_clean, thread_de, threading, udp_rsd, usage(), and VERSION.
short int netlink_loop (unsigned short int queuenum)
Function to create and maintain the NF_QUEUE loop.
netlink loop
Parameters:
[in] queuenum the queue identifier
Returns:
status
References BUFSIZE, errx(), H, NOK, OK, PAYLOADSIZE, and running.
Referenced by main().
void print_trace (void)
Obtain a backtrace and print it to stdout.
print_trace
Referenced by term_signal_handler().
void switch_clean ()
call the packet cleaner
switch_clean
References clean().
Referenced by main().
int term_signal_handler (int signal_nb, siginfo_t * siginfo, void * context)
called when the program receive a signal that should close the program, free memory and delete lock file
term_signal_handler
Parameters:
[in] signal_nb,: number of the signal
[in] siginfo,: informations regarding to the signal
[in] context,: NULL
this will cause the queue loop to stop
References NOK, print_trace(), and running.
Referenced by init_signal().
void usage (char ** argv)
include "pcap_tool.h"
usage function print command line informations
References VERSION.
Referenced by main().