honeybrid: log.c File Reference
log.c File Reference
Log function for honeybrid.
#include <string.h>
#include <syslog.h>
#include <stdio.h>
#include <fcntl.h>
#include <stdlib.h>
#include <unistd.h>
#include <glib.h>
#include <time.h>
#include <sys/time.h>
#include <err.h>
#include "tables.h"
#include "log.h"
Functions
char * log_header (const char *function_name, int id)
return a header for debug log messages, including the timestamp and the name of the function
char * now (void)
return the current timestamp as a string
int honeylog (char *sdata, char *ddata, int level, unsigned id)
add a log entry in the singly linked list
int open_debug_log (void)
int close_connection_log (void)
void open_connection_log (void)
open the file honeybrid.log
void rotate_connection_log (int signal_nb)
rotate the file honeybrid.log every hour
void connection_log (struct conn_struct *conn)
compile a single line of final statistics for every connection handled by honeybrid: Basic flow information: start timestamp, source IP, source Port, destination IP, destination Port, protocol, cumulative flags if TCP INVALID information: duration, reason, packet, byte INIT information: duration, packet, byte DECIDE information: duration, rule, packet id, high interaction ip and port REPLAY information: duration, problem, packet, byte FORWARD information: duration, packet, byte
Variables
unsigned long last_rotation
Detailed Description
Log function for honeybrid.
Author:
Julien Vehent, 2007
Thomas Coquelin, 2008
Function Documentation
int close_connection_log (void)
Referenced by close_conn_tree().
void connection_log (struct conn_struct * conn)
compile a single line of final statistics for every connection handled by honeybrid: Basic flow information: start timestamp, source IP, source Port, destination IP, destination Port, protocol, cumulative flags if TCP INVALID information: duration, reason, packet, byte INIT information: duration, packet, byte DECIDE information: duration, rule, packet id, high interaction ip and port REPLAY information: duration, problem, packet, byte FORWARD information: duration, packet, byte
connection_stat
if log rotation is configured, then we call rotate_connection_log()
Output according to the format configured
g_printerr("%s",logbuf);
ROBIN - 20090326-1007 according to valgrind output
References config, CONTROL, DECISION, conn_struct::decision_rule, DROP, FORWARD, conn_struct::id, INIT, conn_struct::key, conn_struct::protocol, PROXY, REPLAY, conn_struct::replay_problem, rotate_connection_log(), conn_struct::start_microtime, conn_struct::start_timestamp, conn_struct::stat_byte, conn_struct::stat_packet, conn_struct::stat_time, conn_struct::state, conn_struct::total_byte, and conn_struct::total_packet.
Referenced by expire_conn().
int honeylog (char * sdata, char * ddata, int level, unsigned id)
add a log entry in the singly linked list
honeylog
Parameters:
[in] static string pointer
[in] dynamicaly allocated string pointer
[in] log level of event
[in] connection id
Returns:
OK when done, NOK on failure
filter events upon their log level
References LOG_LEVEL, NOK, and OK.
char* log_header (const char * function_name, int id)
return a header for debug log messages, including the timestamp and the name of the function
log_header
References now().
char* now (void)
return the current timestamp as a string
now
References now().
Referenced by log_header(), mod_control(), mod_hash(), mod_source(), and now().
void open_connection_log (void)
open the file honeybrid.log
open log file
Enable line buffer
References config, err(), errx(), and warnx().
Referenced by main().
int open_debug_log (void)
References config, err(), errx(), and warnx().
Referenced by main().
void rotate_connection_log (int signal_nb)
rotate the file honeybrid.log every hour
rotate_connection_log
logfile_name = g_new0(char, 256); logfile_name = g_hash_table_lookup(config,"log_file"); new_name = malloc(sizeof(logfile_name) + 64); sprintf(new_name,"%s.%d%02d%02d_%02d%02d", logfile_name, (1900+tm->tm_year), (1+tm->tm_mon), tm->tm_mday, tm->tm_hour, tm->tm_min);
g_free(logfile_name); free(new_name);
The last step is to update last_rotation
References config, L, last_rotation, LOG_ALL, LOG_HIGH, LOG_LOG, and LOG_MED.
Referenced by connection_log(), and init_signal().
Variable Documentation
unsigned long last_rotation
Referenced by rotate_connection_log().