honeybrid: mod_hash.c File Reference
mod_hash.c File Reference
SHA 1 Module for honeybrid Decision Engine.
#include <string.h>
#include <unistd.h>
#include <ctype.h>
#include <time.h>
#include <sys/time.h>
#include "tables.h"
#include "modules.h"
#include "netcode.h"
Defines
#define HASH_COUNTER 0
array indexes of variables to store for each hash port number will be used as separator (group) hash will be used as key
#define HASH_FIRST_SEEN 1
#define HASH_DURATION 2
#define HASH_PACKET 3
#define HASH_BYTE 4
#define HASH_ASCII 5
Functions
int init_mod_hash ()
void mod_hash (struct mod_args args)
calculate a SHA1 hash value of a packet payload, and look for a possible match in a database of hashes. Parameters required: function = hash; backup = /etc/honeybrid/hash.tb
Variables
const EVP_MD * md
Detailed Description
SHA 1 Module for honeybrid Decision Engine.
This module is called by a boolean decision tree to process a message digest and try to find it in a search table
Author:
Julien Vehent, 2007
Thomas Coquelin, 2008
Define Documentation
#define HASH_ASCII 5
Referenced by mod_hash().
#define HASH_BYTE 4
Referenced by mod_hash().
#define HASH_COUNTER 0
array indexes of variables to store for each hash port number will be used as separator (group) hash will be used as key
Referenced by mod_hash().
#define HASH_DURATION 2
Referenced by mod_hash().
#define HASH_FIRST_SEEN 1
Referenced by mod_hash().
#define HASH_PACKET 3
Referenced by mod_hash().
Function Documentation
int init_mod_hash ()
init OpenSSL SHA-1 engine
References H, and md.
Referenced by init_modules().
void mod_hash (struct mod_args args)
calculate a SHA1 hash value of a packet payload, and look for a possible match in a database of hashes. Parameters required: function = hash; backup = /etc/honeybrid/hash.tb
mod_hash
Parameters:
[in] args,struct that contain the node and the datas to process
[in] user_data,not used
[out] set result to 0 if datas's fingerprint is found in search table, 1 if not
First, we make sure that we have data to work on
get the backup file for this module
We can't decide
get the backup file path for this module
We can't decide
get the IP address from the packet
get the destination port
get the payload from the packet
replace all occurrences of IP addresses by a generic IP
digest the payload
Unknown hash, so we accept the packet
We check if we need to expire this entry
Known hash but entry expired, so we accept the packet
Known hash, so we reject the packet
clean and exit
References node::arg, pkt_struct::conn, conn_struct::count_data_pkt_from_intruder, pkt_struct::data, H, HASH_ASCII, HASH_BYTE, HASH_COUNTER, HASH_DURATION, HASH_FIRST_SEEN, HASH_PACKET, conn_struct::id, node::info_result, pkt_struct::key_dst, md, mod_args::node, now(), pkt_struct::packet, packet::payload, mod_args::pkt, node::result, and save_backup().
Referenced by get_module(), and run_module().
Variable Documentation
const EVP_MD* md
Referenced by init_mod_hash(), and mod_hash().