honeybrid: mod_vmi.c File Reference
mod_vmi.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <errno.h>
#include <netdb.h>
#include <glib.h>
#include <string.h>
#include <unistd.h>
#include <ctype.h>
#include <time.h>
#include <sys/time.h>
#include <pthread.h>
#include "decision_engine.h"
#include "modules.h"
#include "netcode.h"
Data Structures
struct vmi_vm
struct vm_search
struct attacker_search
Macros
#define ATTACK_TIMEOUT 600
Functions
void noop (gpointer data)
void free_vmi_vm (gpointer data)
gboolean build_vmi_vms2 (gpointer key, gpointer value, gpointer data)
void build_vmi_vms (gpointer data, gpointer user_data)
gboolean find_free_vm (gpointer key, gpointer value, gpointer data)
void get_random_vm (struct vm_search *search)
gboolean find_used_vm (gpointer key, gpointer value, gpointer data)
gboolean find_if_banned (gpointer key, gpointer value, gpointer data)
void mod_vmi_front (struct mod_args *args)
void mod_vmi_pick (struct mod_args *args)
void mod_vmi_back (struct mod_args *args)
gboolean control_check_attacker (gpointer key, gpointer value, gpointer data)
void mod_vmi_control (struct mod_args *args)
void mod_vmi (struct mod_args *args)
void vm_status_updater_thread ()
int init_mod_vmi ()
Variables
GThread vmi_status_updater
GTree * vmi_vms
GTree * bannedIPs
int vmi_sock
struct sockaddr_in vmi_addr
unsigned short vmi_port
Macro Definition Documentation
#define ATTACK_TIMEOUT 600
Referenced by control_check_attacker().
Function Documentation
void build_vmi_vms (gpointer data, gpointer user_data)
References target::back_handlers, and build_vmi_vms2().
Referenced by init_mod_vmi().
gboolean build_vmi_vms2 (gpointer key, gpointer value, gpointer data)
References vmi_vm::attacker, vmi_vm::event, H, backend::iface, vmi_vm::lock, vmi_vm::logID, vmi_vm::name, vmi_vm::paused, interface::tag, vmi_sock, vmi_vms, and vmi_vm::vmID.
Referenced by build_vmi_vms().
gboolean control_check_attacker (gpointer key, gpointer value, gpointer data)
References ATTACK_TIMEOUT, vmi_vm::attacker, attacker_search::attacker, vmi_vm::event, attacker_search::event, attacker_search::found, H, vmi_vm::lock, attacker_search::mark, vmi_vm::name, now(), attacker_search::outIP, vmi_vm::paused, vmi_vm::start, attacker_search::vm, and vmi_vm::vmID.
Referenced by mod_vmi_control().
gboolean find_free_vm (gpointer key, gpointer value, gpointer data)
References vmi_vm::attacker, errx(), vmi_vm::event, H, vmi_vm::lock, vmi_vm::logID, vmi_vm::name, vmi_vm::paused, vm_search::srcIP, vmi_vm::start, vm_search::vm, vmi_sock, and vmi_vm::vmID.
gboolean find_if_banned (gpointer key, gpointer value, gpointer data)
References attacker_search::attacker, attacker_search::banned, and attacker_search::srcIP.
Referenced by mod_vmi_pick().
gboolean find_used_vm (gpointer key, gpointer value, gpointer data)
References vmi_vm::attacker, H, vmi_vm::lock, vmi_vm::paused, vm_search::srcIP, vm_search::vm, and vmi_vm::vmID.
Referenced by mod_vmi_front(), and mod_vmi_pick().
void free_vmi_vm (gpointer data)
References vmi_vm::attacker, and vmi_vm::name.
Referenced by init_mod_vmi().
void get_random_vm (struct vm_search * search)
References vmi_vm::attacker, bannedIPs, errx(), vmi_vm::event, vmi_vm::lock, vmi_vm::logID, vmi_vm::name, vmi_vm::paused, vm_search::srcIP, vmi_vm::start, vm_search::vm, vmi_sock, and vmi_vms.
Referenced by mod_vmi_pick().
int init_mod_vmi ()
** MODULE VMI
References bannedIPs, build_vmi_vms(), config, errx(), free_vmi_vm(), H, noop(), targets, vm_status_updater_thread(), vmi_addr, vmi_sock, and vmi_vms.
Referenced by init_modules().
void mod_vmi (struct mod_args * args)
get the backup file for this module
We can't decide
References node::arg, pkt_struct::conn, H, conn_struct::id, mod_vmi_back(), mod_vmi_control(), mod_vmi_front(), mod_vmi_pick(), mod_args::node, mod_args::pkt, and node::result.
void mod_vmi_back (struct mod_args * args)
Referenced by mod_vmi().
void mod_vmi_control (struct mod_args * args)
get the IP address from the packet
References attacker_search::attacker, pkt_struct::conn, control_check_attacker(), attacker_search::event, attacker_search::found, H, conn_struct::honeymon_IDX, conn_struct::id, pkt_struct::key_dst, key_dst, attacker_search::mark, pkt_struct::mark, mod_args::node, attacker_search::outIP, mod_args::pkt, node::result, attacker_search::vm, vmi_sock, and vmi_vms.
Referenced by mod_vmi().
void mod_vmi_front (struct mod_args * args)
References pkt_struct::conn, find_used_vm(), H, conn_struct::id, pkt_struct::key_src, vmi_vm::last_seen, vmi_vm::lock, mod_args::node, vmi_vm::paused, mod_args::pkt, node::result, vm_search::srcIP, vm_search::vm, and vmi_vms.
Referenced by mod_vmi().
void mod_vmi_pick (struct mod_args * args)
References mod_args::backend_use, attacker_search::banned, bannedIPs, pkt_struct::conn, vmi_vm::conn_keys, find_if_banned(), find_used_vm(), get_random_vm(), H, conn_struct::honeymon_IDX, conn_struct::id, conn_struct::key, pkt_struct::key_src, vmi_vm::lock, vmi_vm::logID, mod_args::node, mod_args::pkt, node::result, vm_search::srcIP, attacker_search::srcIP, vm_search::vm, vmi_vms, and vmi_vm::vmID.
Referenced by mod_vmi().
void noop (gpointer data)
Referenced by init_mod_vmi().
void vm_status_updater_thread ()
References vmi_vm::attacker, bannedIPs, conn, vmi_vm::conn_keys, conn_tree, conntreelock, DROP, errx(), vmi_vm::event, H, vmi_vm::lock, vmi_vm::paused, conn_struct::state, vmi_addr, and vmi_vms.
Referenced by init_mod_vmi().
Variable Documentation
GTree* bannedIPs
Referenced by get_random_vm(), init_mod_vmi(), mod_vmi_pick(), and vm_status_updater_thread().
struct sockaddr_in vmi_addr
Referenced by init_mod_vmi(), and vm_status_updater_thread().
unsigned short vmi_port
int vmi_sock
Referenced by build_vmi_vms2(), find_free_vm(), get_random_vm(), init_mod_vmi(), and mod_vmi_control().
GThread vmi_status_updater
GTree* vmi_vms
Referenced by build_vmi_vms2(), get_random_vm(), init_mod_vmi(), mod_vmi_control(), mod_vmi_front(), mod_vmi_pick(), and vm_status_updater_thread().