honeybrid: mod_control.c File Reference
mod_control.c File Reference
Source IP based control engine to rate limit high interaction honeypot.
#include <string.h>
#include <unistd.h>
#include <ctype.h>
#include <time.h>
#include <sys/time.h>
#include "tables.h"
#include "modules.h"
#include "netcode.h"
Functions
void mod_control (struct mod_args args)
calculate the number of packets sent by a same source over a given period of time. If too many packets are sent, following packets are rejected Parameters required: function = hash; backup = /etc/honeybrid/control.tb expiration = 600 max_packet = 1000
Detailed Description
Source IP based control engine to rate limit high interaction honeypot.
Author:
Robin Berthier 2009
Function Documentation
void mod_control (struct mod_args args)
calculate the number of packets sent by a same source over a given period of time. If too many packets are sent, following packets are rejected Parameters required: function = hash; backup = /etc/honeybrid/control.tb expiration = 600 max_packet = 1000
control
Parameters:
[in] pkts,struct that contain the packet to control
[out] set result to 1 if rate limit reached, 0 otherwise
get the IP address from the packet
get the backup file for this module
We can't decide
get the backup file path for this module
We can't decide
get control parameters
no value set for expiration, we go with the default one
no value set for expiration, we go with the default one
20 characters should be enough to hold even very large numbers
counter
first seen
duration
We check if we need to expire this entry
counter
first seen
duration
counter
duration
clean and exit
References node::arg, pkt_struct::conn, H, conn_struct::id, pkt_struct::key_src, mod_args::node, now(), mod_args::pkt, node::result, and save_backup().
Referenced by run_module().