honeybrid: mod_source.c File Reference
mod_source.c File Reference
Source IP based filtering Module for honeybrid Decision Engine.
#include <string.h>
#include <unistd.h>
#include <ctype.h>
#include <time.h>
#include <sys/time.h>
#include "tables.h"
#include "modules.h"
#include "netcode.h"
Functions
void mod_source (struct mod_args args)
check if the source IP has already been seen in a prior connection Parameters required: function = hash; backup = /etc/honeybrid/source.tb
Detailed Description
Source IP based filtering Module for honeybrid Decision Engine.
This module is called by a boolean decision tree to filter attacker based on their IP address
Author:
Robin Berthier 2009
Function Documentation
void mod_source (struct mod_args args)
check if the source IP has already been seen in a prior connection Parameters required: function = hash; backup = /etc/honeybrid/source.tb
mod_source
Parameters:
[in] args,struct that contain the node and the data to process
[in] user_data,not used
[out] set result to 0 if attacker ip is found in search table, 1 if not
get the IP address from the packet
get the backup file for this module
We can't decide
get the backup file path for this module
We can't decide
Unknown IP, so we accept the packet
20 characters should be enough to hold even very large numbers
counter
first seen
duration
We check if we need to expire this entry
Known IP but entry expired, so we accept the packet
counter
first seen
duration
Known IP, so we reject the packet
counter
duration
clean and exit
References node::arg, pkt_struct::conn, H, conn_struct::id, pkt_struct::key_src, mod_args::node, now(), mod_args::pkt, node::result, and save_backup().
Referenced by get_module(), and run_module().