honeybrid: modules.h File Reference
modules.h File Reference
#include <glib.h>
#include <openssl/evp.h>
#include "log.h"
#include "tables.h"
Data Structures
struct mod_args
struct node
Functions
void init_modules ()
setup modules that need to be initialized
void run_module (char *module_name, struct mod_args args)
test of a new function to run module based on module name (without calling get_module)
void(*)(struct mod_args) get_module (char *modname)
return the module function pointer from name
void save_backup_handler ()
This function handles the automatic saving of modules to external files. It works by checking an array in which modules to save have been registered This array is updated after each module run.
int save_backup (GKeyFile *data, char *filename)
This function adds a module backup memory to a queue in order to be written to a file later.
int write_backup (char *filename, GKeyFile *data, void *userdata)
This function write a module backup memory to a file.
void mod_yesno (struct mod_args args)
void mod_counter (struct mod_args args)
void mod_random (struct mod_args args)
int init_mod_hash ()
void mod_hash (struct mod_args args)
calculate a SHA1 hash value of a packet payload, and look for a possible match in a database of hashes. Parameters required: function = hash; backup = /etc/honeybrid/hash.tb
void mod_source (struct mod_args args)
check if the source IP has already been seen in a prior connection Parameters required: function = hash; backup = /etc/honeybrid/source.tb
void mod_control (struct mod_args args)
calculate the number of packets sent by a same source over a given period of time. If too many packets are sent, following packets are rejected Parameters required: function = hash; backup = /etc/honeybrid/control.tb expiration = 600 max_packet = 1000
Variables
GHashTable * module_to_save
const EVP_MD * md
Function Documentation
void(*)(struct mod_args) get_module (char * modname)
return the module function pointer from name
get_module
Parameters:
[in] modname,: module name
Returns:
function pointer to the module
References errx(), H, mod_counter(), mod_hash(), mod_random(), mod_source(), and mod_yesno().
Referenced by yyparse().
int init_mod_hash ()
init OpenSSL SHA-1 engine
References H, and md.
Referenced by init_modules().
void init_modules ()
setup modules that need to be initialized
Todo:
create two functions to handle module backup to file:
a function called by modules to add themselves to a backup queue
a timer event callback function to process the backup queue periodically, and save backups to files
init_modules
create a thread that will save module memory every minute
References errx(), H, init_mod_hash(), module_to_save, and save_backup_handler().
Referenced by main().
void mod_control (struct mod_args args)
calculate the number of packets sent by a same source over a given period of time. If too many packets are sent, following packets are rejected Parameters required: function = hash; backup = /etc/honeybrid/control.tb expiration = 600 max_packet = 1000
** MODULE CONTROL
control
Parameters:
[in] pkts,struct that contain the packet to control
[out] set result to 1 if rate limit reached, 0 otherwise
get the IP address from the packet
get the backup file for this module
We can't decide
get the backup file path for this module
We can't decide
get control parameters
no value set for expiration, we go with the default one
no value set for expiration, we go with the default one
20 characters should be enough to hold even very large numbers
counter
first seen
duration
We check if we need to expire this entry
counter
first seen
duration
counter
duration
clean and exit
References node::arg, pkt_struct::conn, H, conn_struct::id, pkt_struct::key_src, mod_args::node, now(), mod_args::pkt, node::result, and save_backup().
Referenced by run_module().
void mod_counter (struct mod_args args)
** MODULE COUNTER
mod_counter requires the configuration of the following mandatory parameter:
"counter", number of packet to receive before accepting
mod_counter
Parameters:
[in] args,struct that contain the node and the datas to process
[out] set result to 1 packet position match arg, 0 otherwise
We can't decide
We accept this packet
We reject this packet
References node::arg, pkt_struct::conn, conn_struct::count_data_pkt_from_intruder, H, conn_struct::id, mod_args::node, mod_args::pkt, and node::result.
Referenced by get_module(), and run_module().
void mod_hash (struct mod_args args)
calculate a SHA1 hash value of a packet payload, and look for a possible match in a database of hashes. Parameters required: function = hash; backup = /etc/honeybrid/hash.tb
mod_hash
Parameters:
[in] args,struct that contain the node and the datas to process
[in] user_data,not used
[out] set result to 0 if datas's fingerprint is found in search table, 1 if not
First, we make sure that we have data to work on
get the backup file for this module
We can't decide
get the backup file path for this module
We can't decide
get the IP address from the packet
get the destination port
get the payload from the packet
replace all occurrences of IP addresses by a generic IP
digest the payload
Unknown hash, so we accept the packet
We check if we need to expire this entry
Known hash but entry expired, so we accept the packet
Known hash, so we reject the packet
clean and exit
References node::arg, pkt_struct::conn, conn_struct::count_data_pkt_from_intruder, pkt_struct::data, H, HASH_ASCII, HASH_BYTE, HASH_COUNTER, HASH_DURATION, HASH_FIRST_SEEN, HASH_PACKET, conn_struct::id, node::info_result, pkt_struct::key_dst, md, mod_args::node, now(), pkt_struct::packet, packet::payload, mod_args::pkt, node::result, and save_backup().
Referenced by get_module(), and run_module().
void mod_random (struct mod_args args)
** MODULE RANDOM
mod_random requires the configuration of the following mandatory parameter:
"value", to define a basis for the probability to accept the packet, which is 1 out of value
mod_random
Parameters:
[in] args,struct that contain the node and the data to process
getting the value provided as parameter
We can't decide
We can't decide
deciding based on a probability of 1 out of "value":
We accept this packet
We reject this packet
References node::arg, pkt_struct::conn, H, conn_struct::id, mod_args::node, mod_args::pkt, and node::result.
Referenced by get_module(), and run_module().
void mod_source (struct mod_args args)
check if the source IP has already been seen in a prior connection Parameters required: function = hash; backup = /etc/honeybrid/source.tb
** MODULE SOURCE
mod_source
Parameters:
[in] args,struct that contain the node and the data to process
[in] user_data,not used
[out] set result to 0 if attacker ip is found in search table, 1 if not
get the IP address from the packet
get the backup file for this module
We can't decide
get the backup file path for this module
We can't decide
Unknown IP, so we accept the packet
20 characters should be enough to hold even very large numbers
counter
first seen
duration
We check if we need to expire this entry
Known IP but entry expired, so we accept the packet
counter
first seen
duration
Known IP, so we reject the packet
counter
duration
clean and exit
References node::arg, pkt_struct::conn, H, conn_struct::id, pkt_struct::key_src, mod_args::node, now(), mod_args::pkt, node::result, and save_backup().
Referenced by get_module(), and run_module().
void mod_yesno (struct mod_args args)
************ [Basic Modules]
** MODULE YESNO
mod_yesno requires the configuration of the following mandatory parameter:
"value", if 0 it rejects everything, if 1 it accepts everything
mod_yesno
Parameters:
[in] args,struct that contain the node and the datas to process
[out] set result to 1 when 'arg' is "yes", 0 otherwise
We can't decide
We accept this packet
We reject this packet
References node::arg, pkt_struct::conn, H, conn_struct::id, mod_args::node, mod_args::pkt, and node::result.
Referenced by get_module(), and run_module().
void run_module (char * module_name, struct mod_args args)
test of a new function to run module based on module name (without calling get_module)
run_module
References pkt_struct::conn, H, conn_struct::id, mod_control(), mod_counter(), mod_hash(), mod_random(), mod_source(), mod_yesno(), mod_args::node, mod_args::pkt, and node::result.
Referenced by decide().
int save_backup (GKeyFile * data, char * filename)
This function adds a module backup memory to a queue in order to be written to a file later.
save_backup
References H, and module_to_save.
Referenced by mod_control(), mod_hash(), and mod_source().
void save_backup_handler ()
This function handles the automatic saving of modules to external files. It works by checking an array in which modules to save have been registered This array is updated after each module run.
save_backup_handler
saving module every 60 seconds
References H, module_to_save, OK, threading, and write_backup().
Referenced by init_modules().
int write_backup (char * filename, GKeyFile * data, void * userdata)
This function write a module backup memory to a file.
write_backup
References H.
Referenced by save_backup_handler().
Variable Documentation
const EVP_MD* md
*********** [Advanced Modules]
** MODULE HASH
GHashTable* module_to_save
Referenced by init_modules(), save_backup(), and save_backup_handler().