honeybrid: modules.c File Reference
modules.c File Reference
#include <stdio.h>
#include <string.h>
#include <err.h>
#include <stdlib.h>
#include <glib.h>
#include <glib/gprintf.h>
#include <glib/gstdio.h>
#include <unistd.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "modules.h"
#include "log.h"
Functions
void init_modules ()
setup modules that need to be initialized
void run_module (char *module_name, struct mod_args args)
test of a new function to run module based on module name (without calling get_module)
void(*)(struct mod_args) get_module (char *modname)
return the module function pointer from name
int write_backup (char *filename, GKeyFile *data, void *userdata)
This function write a module backup memory to a file.
void save_backup_handler ()
This function handles the automatic saving of modules to external files. It works by checking an array in which modules to save have been registered This array is updated after each module run.
int save_backup (GKeyFile *data, char *filename)
This function adds a module backup memory to a queue in order to be written to a file later.
Function Documentation
void(*)(struct mod_args) get_module (char * modname)
return the module function pointer from name
get_module
Parameters:
[in] modname,: module name
Returns:
function pointer to the module
References errx(), H, mod_counter(), mod_hash(), mod_random(), mod_source(), and mod_yesno().
Referenced by yyparse().
void init_modules ()
setup modules that need to be initialized
Todo:
create two functions to handle module backup to file:
a function called by modules to add themselves to a backup queue
a timer event callback function to process the backup queue periodically, and save backups to files
init_modules
create a thread that will save module memory every minute
References errx(), H, init_mod_hash(), module_to_save, and save_backup_handler().
Referenced by main().
void run_module (char * module_name, struct mod_args args)
test of a new function to run module based on module name (without calling get_module)
run_module
References pkt_struct::conn, H, conn_struct::id, mod_control(), mod_counter(), mod_hash(), mod_random(), mod_source(), mod_yesno(), mod_args::node, mod_args::pkt, and node::result.
Referenced by decide().
int save_backup (GKeyFile * data, char * filename)
This function adds a module backup memory to a queue in order to be written to a file later.
save_backup
References H, and module_to_save.
Referenced by mod_control(), mod_hash(), and mod_source().
void save_backup_handler ()
This function handles the automatic saving of modules to external files. It works by checking an array in which modules to save have been registered This array is updated after each module run.
save_backup_handler
saving module every 60 seconds
References H, module_to_save, OK, threading, and write_backup().
Referenced by init_modules().
int write_backup (char * filename, GKeyFile * data, void * userdata)
This function write a module backup memory to a file.
write_backup
References H.
Referenced by save_backup_handler().