honeybrid: netcode.c File Reference
netcode.c File Reference
Network functions file.
#include <glib.h>
#include <string.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <stdlib.h>
#include <stdio.h>
#include "log.h"
#include "tables.h"
#include "netcode.h"
Functions
unsigned short in_cksum (unsigned short *addr, int len)
Checksum routine for Internet Protocol family headers.
int send_raw (struct iphdr *p)
send a packet over a raw socket
int forward (struct pkt_struct *pkt)
forward the packet to the attacker or to the HIH according to its origin
int reply_reset (struct packet p)
creat a RST packet from a unexepcted packet and sends it with send_raw
int reset_lih (struct conn_struct *conn)
reset the LIH when redirected to HIH
int replay (struct conn_struct *conn, struct pkt_struct *pkt)
reset the LIH when redirected to HIH
int hb_ip_checksum (struct iphdr *hdr)
update the checksum in the IP header
int udp_checksum (struct udp_packet *hdr)
update the checksum in the UDP header
int define_expected_data (struct pkt_struct *pkt)
define expected packet from HIH according to the packet from LIH
int test_expected (struct conn_struct *conn, struct pkt_struct *pkt)
get the packet from HIH, compare it to expected data, drop it and return the comparison result
int init_raw_sockets ()
create the two raw sockets for UDP/IP and TCP/IP
int tcp_checksum (struct tcp_packet *pkt)
Detailed Description
Network functions file.
Author:
Julien Vehent, 2007
Thomas Coquelin, 2008
Function Documentation
int define_expected_data (struct pkt_struct * pkt)
define expected packet from HIH according to the packet from LIH
define_expected_data
Parameters:
[in] pkt,: packet metadata used
References pkt_struct::conn, hih_struct::delta, conn_struct::expected_data, conn_struct::hih, packet::ip, expected_data_struct::ip_proto, conn_struct::lock, OK, pkt_struct::packet, packet::payload, expected_data_struct::payload, packet::tcp, expected_data_struct::tcp_ack_seq, and expected_data_struct::tcp_seq.
Referenced by replay(), and setup_redirection().
int forward (struct pkt_struct * pkt)
forward the packet to the attacker or to the HIH according to its origin
forward
Parameters:
[in] pkt,the packet metadata structure to forward
Returns:
OK if the packet has been succesfully sent
If packet from HIH, we forward if to EXT with LIH source
We set LIH source IP
If TCP, we update the source port, the sequence number, and the checksum
If UDP, we update the source port and the checksum
If packet from EXT, we forward if to HIH
If packet from HIH, we forward if to EXT with LIH source
If TCP, we update the destination port, the acknowledgement number if any, and the checksum
If UDP, we update the destination port and the checksum
we update the IP checksum and send the packect
References hih_struct::addr, pkt_struct::conn, hih_struct::delta, EXT, H, hb_ip_checksum(), conn_struct::hih, HIH, conn_struct::id, packet::ip, hih_struct::lih_addr, NOK, OK, pkt_struct::origin, pkt_struct::packet, hih_struct::port, send_raw(), tcp_packet::tcp, packet::tcp, tcp_checksum(), and udp_checksum().
Referenced by replay(), and setup_redirection().
int hb_ip_checksum (struct iphdr * hdr)
update the checksum in the IP header
hb_ip_checksum
References in_cksum(), and OK.
Referenced by forward(), and reply_reset().
unsigned short in_cksum (unsigned short * addr, int len)
Checksum routine for Internet Protocol family headers.
in_cksum
Parameters:
[in] addr a pointer to the data
[in] len the 32 bits data size
Returns:
sum a 16 bits checksum
Our algorithm is simple, using a 32 bit accumulator (sum), we add sequential 16 bit words to it, and at the end, fold back all the carry bits from the top 16 bits into the lower 16 bits.
mop up an odd byte, if necessary
add back carry outs from top 16 bits to low 16 bits
add hi 16 to low 16
add carry
truncate to 16 bits
Referenced by hb_ip_checksum(), tcp_checksum(), and udp_checksum().
int init_raw_sockets ()
create the two raw sockets for UDP/IP and TCP/IP
init_raw_sockets
Returns:
OK
create the two raw sockets for UDP/IP and TCP/IP
References OK, tcp_rsd, and udp_rsd.
Referenced by main().
int replay (struct conn_struct * conn, struct pkt_struct * pkt)
reset the LIH when redirected to HIH
replay
Parameters:
[in] conn,: the connnection being replayed
[in] pkt,: the packet from HIH to test
If packet is from HIH and matches expected data then we replay the following packets from EXT to HIH until we find a packet from LIH
Then we define expected data according to that packet
References conn_struct::BUFFER, pkt_struct::DE, define_expected_data(), EXT, FORWARD, forward(), free_pkt(), H, HIH, conn_struct::id, NOK, OK, pkt_struct::origin, conn_struct::replay_id, switch_state(), and test_expected().
int reply_reset (struct packet p)
creat a RST packet from a unexepcted packet and sends it with send_raw
reply_reset
Parameters:
[in] p,the packet to which we reply the reset packet
reset only tcp connections
fill up the IP header
fill up the TCP header
References H, hb_ip_checksum(), tcp_packet::ip, packet::ip, NOK, send_raw(), packet::tcp, and tcp_checksum().
int reset_lih (struct conn_struct * conn)
reset the LIH when redirected to HIH
reset_lih
Parameters:
[in] conn,: the connnection that the LIH reset
find last packet from LIH
call reply_reset() with this packet
References conn_struct::BUFFER, H, conn_struct::id, packet::ip, LIH, NOK, pkt_struct::origin, and pkt_struct::packet.
Referenced by setup_redirection().
int send_raw (struct iphdr * p)
send a packet over a raw socket
send_raw
Parameters:
[in] p,the packet structure that contains the packet to be sent
Returns:
OK if the packet has been succesfully sent
This line seg fault... sprintf(logbuf, "send_raw():\tSending raw packet from %s to %s\n", inet_ntoa(*(struct in_addr*)p->saddr), inet_ntoa(*(struct in_addr*)p->daddr));
If TCP, use the TCP raw socket
dst.sin_port = ((struct tcp_packet*)p)->tcp.dest;
If UDP, use the UDP raw socket
References H, NOK, OK, tcp_rsd, and udp_rsd.
Referenced by forward(), and reply_reset().
int tcp_checksum (struct tcp_packet * pkt)
test for a new tcp checksum function
Parameters:
[in] pkt,: packet to compute the checksum
Returns:
OK
References pseudotcphdr::daddr, in_cksum(), tcp_packet::ip, OK, tcp_packet::payload, tcp_chk_packet::payload, pseudotcphdr::proto, tcp_chk_packet::pseudohdr, pseudotcphdr::res1, pseudotcphdr::saddr, tcp_chk_packet::tcp, tcp_packet::tcp, and pseudotcphdr::tcp_len.
Referenced by forward(), and reply_reset().
int test_expected (struct conn_struct * conn, struct pkt_struct * pkt)
get the packet from HIH, compare it to expected data, drop it and return the comparison result
test_expected
lock the structure g_static_rw_lock_writer_lock(&conn->lock);
free the lock g_static_rw_lock_writer_unlock(&conn->lock);
References pkt_struct::data, conn_struct::expected_data, H, conn_struct::id, packet::ip, expected_data_struct::ip_proto, NOK, OK, pkt_struct::packet, expected_data_struct::payload, packet::payload, conn_struct::replay_problem, packet::tcp, expected_data_struct::tcp_ack_seq, and expected_data_struct::tcp_seq.
Referenced by replay().
int udp_checksum (struct udp_packet * hdr)
update the checksum in the UDP header
udp_checksum
References in_cksum(), OK, and udp_packet::udp.
Referenced by forward().