honeybrid: pcap_tool.c File Reference
pcap_tool.c File Reference
Pcap function to record communications.
#include <sys/time.h>
#include <glib.h>
#include "pcap_tool.h"
#include "tables.h"
#include "log.h"
Functions
GString * create_pcap_filename (int mode)
create a filename based on the configuration and a time value
int init_pcap_context ()
create the pcap descriptors
int record_pkt (struct nfq_data *tb, char *p, int mode)
record a packet in the current pcap file descriptor
int close_pcap_context ()
Detailed Description
Pcap function to record communications.
J. Vehent
Function Documentation
int close_pcap_context ()
close_pcap_context, close the descriptors
Parameters:
[in] \return 0 on success, anything else otherwise
References pcap_main_desc, pcap_output_current, and pcap_output_redirected.
GString* create_pcap_filename (int mode)
create a filename based on the configuration and a time value
create_pcap_filename
Parameters:
[in] mode,0 for non redirected file name, 1 for redirected file name
Returns:
a GString structure
prefix = value from the config file
add the current time
and finally, the '.pcap' extension
return the structure GString created
References config.
Referenced by init_pcap_context(), and record_pkt().
int init_pcap_context ()
create the pcap descriptors
init_pcap_context
Returns:
0 on success, anything else otherwise
pcap_open_dead, open offline context for pcap
Parameters:
[in] DLT_RAW,assume incoming packet doesn't have a layer 2 header (netfilter requierement)
[in] BUFSIZE,max size of a packet
Returns:
pcap_main_desc, a descriptor to the pcap context
L(32,"INIT_PCAP_CONTEXT",NULL,5);
create output filename based on the conf and the time value
pcap_dump_open, create an output file descriptor for this context
Parameters:
[in] pcap_main_desc,a descriptor to the pcap context
[in] output_file_name->str,the filename
Returns:
pcap_output_current, a pcap file descriptor
L(33,"INIT_PCAP_CONTEXT",NULL, 5);
L(34,"INIT_PCAP_CONTEXT",output_file_name->str, 5);
create output filename for redirected connections
same for output of redirected connections
L(35,"INIT_PCAP_CONTEXT",NULL, 5);
L(34,"INIT_PCAP_CONTEXT",redirected_output_file_name->str, 5);
References create_pcap_filename(), pcap_main_desc, pcap_output_current, pcap_output_redirected, and PCAPSIZE.
Referenced by record_pkt().
int record_pkt (struct nfq_data * tb, char * p, int mode)
record a packet in the current pcap file descriptor
record_pkt
Parameters:
[in] nfq_data *tb, raw packet (used with nfqueue)
[in] *payload,packet to record (used outside of nfqueue)
[in] mode,0 for non redirected connection, 1 for redirected connections, 2 for redirected outside nfqueue, 3 for non redirected outside nfqueue
Returns:
0 on success, anything else otherwise
if pcap desc doesn't exist, init pcap context
switch the descriptor regarding to the mode (redirected or not)
if the actual pcap output file is bigger than 10mo, create a new one
close the current descriptor
create output filename based on the conf and the time value
open the new file descriptor
L(33,"RECORD_PKT",file_name->str, 5);
L(34,"RECORD_PKT",file_name->str,5);
store new descriptor in global descriptor
create pcap specific header
mode 2 and 3 are used when we need to record a packet received outside of the netfilter queue
+1 because the '' is not included
pcap_dump, write pcap header and packet data to the output file
Parameters:
[in] pcap_output_current,descriptor to the current output file
[in] &phdr,pcap header
[in] payload,packet data
pcap_dump, write pcap header and packet data to the output file
Parameters:
[in] pcap_output_current,descriptor to the current output file
[in] &phdr,pcap header
[in] (const u_char *)nf_packet, packet data from netfilter queue
L(36,"RECORD_PKT",NULL, 5);
References create_pcap_filename(), init_pcap_context(), pcap_main_desc, pcap_output_current, and pcap_output_redirected.