honeybrid: syntax.c File Reference
syntax.c File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <pcap.h>
#include <dumbnet.h>
#include <glib.h>
#include "rules.h"
#include <unistd.h>
Data Structures
struct yy_buffer_state
struct yy_trans_info
Defines
#define YY_INT_ALIGNED short int
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#define FLEX_BETA
#define INT8_MIN (-128)
#define INT16_MIN (-32767-1)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT16_MAX (32767)
#define INT32_MAX (2147483647)
#define UINT8_MAX (255U)
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define yyconst
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define BEGIN (yy_start) = 1 + 2 *
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE yyrestart(yyin)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define YY_LESS_LINENO(n)
#define yyless(n)
#define unput(c) yyunput(c, (yytext_ptr))
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER)
#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define yytext_ptr yytext
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 20
#define YY_END_OF_BUFFER 21
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define YY_NO_INPUT
#define INITIAL 0
#define YY_EXTRA_TYPE void *
#define YY_READ_BUF_SIZE 8192
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
#define YY_INPUT(buf, result, max_size)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg)
#define YY_DECL_IS_OURS 1
#define YY_DECL int yylex (void)
#define YY_BREAK break;
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_EXIT_FAILURE 2
#define yyless(n)
#define YYTABLES_NAME "yytables"
Typedefs
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef size_t yy_size_t
typedef unsigned char YY_CHAR
typedef int yy_state_type
Functions
void yyrestart (FILE *input_file)
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
YY_BUFFER_STATE yy_create_buffer (FILE *file, int size)
void yy_delete_buffer (YY_BUFFER_STATE b)
void yy_flush_buffer (YY_BUFFER_STATE b)
Discard all buffered characters.
void yypush_buffer_state (YY_BUFFER_STATE new_buffer)
Pushes the new state onto the stack.
void yypop_buffer_state (void)
Removes and deletes the top of the stack, if present.
YY_BUFFER_STATE yy_scan_buffer (char *base, yy_size_t size)
Setup the input buffer state to scan directly from a user-specified character buffer.
YY_BUFFER_STATE yy_scan_string (yyconst char *yystr)
Setup the input buffer state to scan a string.
YY_BUFFER_STATE yy_scan_bytes (yyconst char *yybytes, int _yybytes_len)
Setup the input buffer state to scan the given bytes.
void * yyalloc (yy_size_t)
void * yyrealloc (void *, yy_size_t)
void yyfree (void *)
int yylex_destroy (void)
int yyget_debug (void)
void yyset_debug (int debug_flag)
YY_EXTRA_TYPE yyget_extra (void)
void yyset_extra (YY_EXTRA_TYPE user_defined)
FILE * yyget_in (void)
Get the input stream.
void yyset_in (FILE *in_str)
Set the input stream.
FILE * yyget_out (void)
Get the output stream.
void yyset_out (FILE *out_str)
int yyget_leng (void)
Get the length of the current token.
char * yyget_text (void)
Get the current token.
int yyget_lineno (void)
Get the current line number.
void yyset_lineno (int line_number)
Set the current line number.
int yywrap (void)
int yylex (void)
Variables
int yyleng
FILE * yyin = (FILE *) 0
FILE * yyout = (FILE *) 0
int yylineno = 1
char * yytext
int yy_flex_debug = 0
Define Documentation
#define BEGIN (yy_start) = 1 + 2 *
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define FLEX_BETA
#define FLEX_SCANNER
#define INITIAL 0
#define INT16_MAX (32767)
#define INT16_MIN (-32767-1)
#define INT32_MAX (2147483647)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT8_MIN (-128)
#define REJECT reject_used_but_not_detected
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define UINT8_MAX (255U)
#define unput (c) yyunput(c, (yytext_ptr))
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define YY_BREAK break;
#define YY_BUF_SIZE 16384
#define YY_BUFFER_EOF_PENDING 2
#define YY_BUFFER_NEW 0
Referenced by yy_flush_buffer(), and yy_scan_buffer().
#define YY_BUFFER_NORMAL 1
#define YY_CURRENT_BUFFER
Value:
((yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
Referenced by yy_flush_buffer(), yylex_destroy(), yypop_buffer_state(), and yypush_buffer_state().
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]
Referenced by yylex_destroy(), yypop_buffer_state(), and yypush_buffer_state().
#define YY_DECL int yylex (void)
#define YY_DECL_IS_OURS 1
#define YY_DO_BEFORE_ACTION
Value:
(yytext_ptr) = yy_bp; \
        yyleng = (size_t) (yy_cp - yy_bp); \
        (yy_hold_char) = *yy_cp; \
        *yy_cp = '\0'; \
        (yy_c_buf_p) = yy_cp;
#define YY_END_OF_BUFFER 21
#define YY_END_OF_BUFFER_CHAR 0
Referenced by yy_flush_buffer(), yy_scan_buffer(), and yy_scan_bytes().
#define YY_EXIT_FAILURE 2
#define YY_EXTRA_TYPE void *
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg)
Referenced by yy_scan_buffer(), and yy_scan_bytes().
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER)
#define YY_INPUT (buf, result, max_size)
Value:
if (YY_CURRENT_BUFFER_LVALUE->yy_is_interactive) \
                { \
                int c = '*'; \
                size_t n; \
                for ( n = 0; n < max_size && \
                             (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
                        buf[n] = (char) c; \
                if ( c == '\n' ) \
                        buf[n++] = (char) c; \
                if ( c == EOF && ferror( yyin ) ) \
                        YY_FATAL_ERROR( "input in flex scanner failed" ); \
                result = n; \
                } \
        else \
                { \
                errno=0; \
                while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
                        { \
                        if( errno != EINTR) \
                                { \
                                YY_FATAL_ERROR( "input in flex scanner failed" ); \
                                break; \
                                } \
                        errno=0; \
                        clearerr(yyin); \
                        } \
                }\
\
#define YY_INT_ALIGNED short int
#define YY_LESS_LINENO (n)
#define YY_MORE_ADJ 0
#define yy_new_buffer yy_create_buffer
#define YY_NEW_FILE yyrestart(yyin)
#define YY_NO_INPUT
#define YY_NULL 0
#define YY_NUM_RULES 20
#define YY_READ_BUF_SIZE 8192
#define YY_RESTORE_YY_MORE_OFFSET
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_SC_TO_UI (c) ((unsigned int) (unsigned char) c)
#define yy_set_bol (at_bol)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
                YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
        } \
        YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
        }
#define yy_set_interactive (is_interactive)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
                YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
        } \
        YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
        }
#define YY_START (((yy_start) - 1) / 2)
#define YY_START_STACK_INCR 25
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
#define yyconst
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                yytext[yyleng] = (yy_hold_char); \
                (yy_c_buf_p) = yytext + yyless_macro_arg; \
                (yy_hold_char) = *(yy_c_buf_p); \
                *(yy_c_buf_p) = '\0'; \
                yyleng = yyless_macro_arg; \
                } \
        while ( 0 )
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                *yy_cp = (yy_hold_char); \
                YY_RESTORE_YY_MORE_OFFSET \
                (yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
                YY_DO_BEFORE_ACTION; /* set up yytext again */ \
                } \
        while ( 0 )
#define yymore () yymore_used_but_not_detected
#define YYSTATE YY_START
#define YYTABLES_NAME "yytables"
#define yyterminate () return YY_NULL
#define yytext_ptr yytext
Typedef Documentation
typedef short int flex_int16_t
typedef int flex_int32_t
typedef signed char flex_int8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef unsigned char flex_uint8_t
typedef struct yy_buffer_state* YY_BUFFER_STATE
typedef unsigned char YY_CHAR
typedef size_t yy_size_t
typedef int yy_state_type
Function Documentation
YY_BUFFER_STATE yy_create_buffer (FILE * file, int size)
void yy_delete_buffer (YY_BUFFER_STATE b)
Referenced by yylex_destroy(), and yypop_buffer_state().
void yy_flush_buffer (YY_BUFFER_STATE b)
Discard all buffered characters.
On the next scan, YY_INPUT will be called.
Parameters:
b the buffer state to be flushed, usually YY_CURRENT_BUFFER.
References yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, and yy_buffer_state::yy_n_chars.
YY_BUFFER_STATE yy_scan_buffer (char * base, yy_size_t size)
Setup the input buffer state to scan directly from a user-specified character buffer.
Parameters:
base the character buffer
size the size in bytes of the character buffer
Returns:
the newly allocated buffer state object.
References yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, yy_buffer_state::yy_n_chars, yy_switch_to_buffer(), and yyalloc().
Referenced by yy_scan_bytes().
YY_BUFFER_STATE yy_scan_bytes (yyconst char * yybytes, int _yybytes_len)
Setup the input buffer state to scan the given bytes.
The next call to yylex() will scan from a copy of bytes.
Parameters:
yybytes the byte buffer to scan
_yybytes_len the number of bytes in the buffer pointed to by bytes.
Returns:
the newly allocated buffer state object.
References YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_is_our_buffer, yy_scan_buffer(), and yyalloc().
Referenced by yy_scan_string().
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr)
Setup the input buffer state to scan a string.
The next call to yylex() will scan from a copy of str.
Parameters:
yystr a NUL-terminated string to scan
Returns:
the newly allocated buffer state object.
Note:
If you want to scan bytes that may contain NUL values, then use yy_scan_bytes() instead.
References yy_scan_bytes().
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
Referenced by yy_scan_buffer().
void * yyalloc (yy_size_t size)
Referenced by yy_scan_buffer(), and yy_scan_bytes().
void yyfree (void * ptr)
Referenced by yylex_destroy().
int yyget_debug (void)
YY_EXTRA_TYPE yyget_extra (void)
FILE * yyget_in (void)
Get the input stream.
References yyin.
int yyget_leng (void)
Get the length of the current token.
References yyleng.
int yyget_lineno (void)
Get the current line number.
FILE * yyget_out (void)
Get the output stream.
References yyout.
char * yyget_text (void)
Get the current token.
int yylex (void)
int yylex_destroy (void)
References YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_delete_buffer(), yyfree(), and yypop_buffer_state().
void yypop_buffer_state (void)
Removes and deletes the top of the stack, if present.
The next element becomes the new top.
References YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yy_delete_buffer().
Referenced by yylex_destroy().
void yypush_buffer_state (YY_BUFFER_STATE new_buffer)
Pushes the new state onto the stack.
The new state becomes the current state. This function will allocate the stack if necessary.
Parameters:
new_buffer The new state.
References YY_CURRENT_BUFFER, and YY_CURRENT_BUFFER_LVALUE.
void * yyrealloc (void * ptr, yy_size_t size)
void yyrestart (FILE * input_file)
void yyset_debug (int debug_flag)
void yyset_extra (YY_EXTRA_TYPE user_defined)
void yyset_in (FILE * in_str)
Set the input stream.
This does not discard the current input buffer.
Parameters:
in_str A readable stream.
See also:
yy_switch_to_buffer
References yyin.
void yyset_lineno (int line_number)
Set the current line number.
Parameters:
line_number
void yyset_out (FILE * out_str)
References yyout.
int yywrap (void)
should return 0 if additional input has to be parsed, 1 if the end has been reached
Variable Documentation
int yy_flex_debug = 0
FILE* yyin = (FILE *) 0
int yyleng
Referenced by yyget_leng().
int yylineno = 1
FILE * yyout = (FILE *) 0
Referenced by yyget_out(), and yyset_out().
char* yytext