honeybrid: tables.c File Reference
tables.c File Reference
Information tables file.
#include <netinet/tcp.h>
#include <netinet/ip.h>
#include <netinet/udp.h>
#include <arpa/inet.h>
#include <pcap.h>
#include <time.h>
#include <sys/time.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dumbnet.h>
#include <ctype.h>
#include "tables.h"
#include "log.h"
#include "netcode.h"
Defines
#define CONCALLSIZE 2048
number of bytes of the buffer in the netfilter callback function
Functions
void print_hex_ascii_line (const u_char *payload, int len, int offset)
void print_payload (const u_char *payload, int len)
char * lookup_proto (int proto)
char * lookup_origin (int origin)
char * lookup_state (int state)
int switch_state (struct conn_struct *conn, int new_state)
int init_pkt (char *nf_packet, struct pkt_struct *pkt)
init the current packet structure with meta-information such as the origin and the number of bytes of data
int free_pkt (struct pkt_struct *pkt)
free the current packet structure
int init_conn (struct pkt_struct *pkt, struct conn_struct **conn)
init the current context using the tuples
int addr2int (char *address)
Convert an IP address from string to int.
int test_honeypot_addr (char *key, int list)
compare an IP with a list of honeypot addresses
char * lookup_honeypot_addr (gchar *testkey, int list)
return the low/high interaction honeypot currently associated with the low/high interaction honeypot in argument
int store_pkt (struct conn_struct *conn, struct pkt_struct *pkt)
Store the current packet as part of the connection to replay it later. If this is the first packet of a communication, init its structure in the main B-Tree.
int expire_conn (gpointer key, struct conn_struct *conn, gint *expiration_delay)
called for each entry in the B-Tree, if a time value is upper to "expiration_delay" (default is 120 sec) and the connection is not marked as redirected, entry is deleted
void free_conn (gpointer key, gpointer trash)
called for each entry in the pointer array, each entry is a key that is deleted from the B-Tree
void clean ()
watchman for the b_tree, wake up every 5 minutes and check every entries
int setup_redirection (struct conn_struct *conn)
called for each connection being redirected to setup and start the redirection process
char * config_lookup (char *parameter)
Detailed Description
Information tables file.
In this file are defined the functions to manage packets. TBU
Author:
Julien Vehent, 2007
Thomas Coquelin, 2008
Define Documentation
#define CONCALLSIZE 2048
number of bytes of the buffer in the netfilter callback function
Function Documentation
int addr2int (char * address)
Convert an IP address from string to int.
addr2int
Parameters:
[in] the IP address (string format)
Returns:
the IP address (int format)
References H.
Referenced by setup_redirection(), and test_honeypot_addr().
void clean ()
watchman for the b_tree, wake up every 5 minutes and check every entries
clean
wake up every second
init the table
call the clean function for each value, delete the value if TRUE is returned
remove each key listed from the btree
free the array
References config, conn_tree, entrytoclean, expire_conn(), free_conn(), OK, and threading.
Referenced by switch_clean().
char* config_lookup (char * parameter)
config_lookup /brief lookup values from the config hash table. Make sure the required value is present
References config, and errx().
int expire_conn (gpointer key, struct conn_struct * conn, gint * expiration_delay)
called for each entry in the B-Tree, if a time value is upper to "expiration_delay" (default is 120 sec) and the connection is not marked as redirected, entry is deleted
expire_conn
Parameters:
[in] key,a pointer to the current B-Tree key value
[in] conn,a pointer to the current B-Tree associated value
[in] expiration_delay
Returns:
FALSE, to continue to traverse the tree (if TRUE is returned, traversal is stopped)
output final statistics about the connection
lock the structure, this will never be unlocked
remove the singly linked lists
g_free(conn->key_hih); free(conn->decision_rule);
list the entry for later removal
References conn_struct::access_time, conn_struct::BUFFER, connection_log(), conn_struct::decision_rule, entrytoclean, free_pkt(), H, conn_struct::id, INIT, conn_struct::key_ext, conn_struct::key_lih, conn_struct::lock, and conn_struct::state.
Referenced by clean(), and close_conn_tree().
void free_conn (gpointer key, gpointer trash)
called for each entry in the pointer array, each entry is a key that is deleted from the B-Tree
free_conn
Parameters:
[in] key,a pointer to the current B-Tree key value stored in the pointer table
[in] trash,user data, unused
References conn_tree, H, and rwlock.
Referenced by clean(), and close_conn_tree().
int free_pkt (struct pkt_struct * pkt)
free the current packet structure
free_pkt
Parameters:
[in] pkt,: struct pkt_struct to free
Returns:
OK
References packet::FRAME, packet::ip, pkt_struct::key, pkt_struct::key_dst, pkt_struct::key_src, NOK, OK, and pkt_struct::packet.
Referenced by expire_conn(), and replay().
int init_conn (struct pkt_struct * pkt, struct conn_struct ** conn)
init the current context using the tuples
init_conn
Parameters:
[in] pkt,: struct pkt_struct to work with
[in] conn,: struct conn_struct to work with
Returns:
0 if success, anything else otherwise
Get current time to update or create the structure
if key->str is null, then we have a seg fault! And it can happen if no LIH was found from a HIH->EXT packet... if (pkt->key == NULL) { g_printerr("%s key is NULL, no valid connection attached\n", H(4)); return NOK; }
The key could not be found, so we need to figure out where this packet comes from
Try to match a target with this packet
If not, then it means the packets is either originated from a honeypot inside (we control) or from a non supported external host (we drop)
check if the src is in the honeynet
if not, then this packet is for an unconfigured target, we drop it
IPs match, we can proceed
destination address is not the LIH address, so we drop the packet (later we might NAT
Todo:
)
Init new connection structure
fill the structure
statistics
conn_init->decision_rule = malloc(512);
insert entry in B-Tree (set up a lock to protect the writing)
free the lock
store new entry in current struct
The key was found in the B-Tree
We store control statistics in the proxy mode
statistics
We update the current connection access time
References conn_struct::access_time, conn_struct::BUFFER, c_id, pkt_struct::conn, conn_tree, CONTROL, conn_struct::count_data_pkt_from_intruder, conn_struct::count_data_pkt_from_lih, conn_struct::decision_rule, hih_struct::delta, ETHER_HDR_LEN, EXT, packet::FRAME, H, high_redirection_table, conn_struct::hih, HIH, conn_struct::id, INIT, INVALID, conn_struct::invalid_problem, packet::ip, conn_struct::key, pkt_struct::key, pkt_struct::key_dst, conn_struct::key_ext, conn_struct::key_hih, conn_struct::key_lih, pkt_struct::key_src, LIH, hih_struct::lih_syn_seq, conn_struct::lock, NOK, OK, pkt_struct::origin, pkt_struct::packet, conn_struct::protocol, PROXY, conn_struct::replay_id, conn_struct::replay_problem, rwlock, pkt_struct::size, conn_struct::start_microtime, conn_struct::start_timestamp, conn_struct::stat_byte, conn_struct::stat_packet, conn_struct::stat_time, conn_struct::state, conn_struct::target, targets, packet::tcp, conn_struct::total_byte, and conn_struct::total_packet.
int init_pkt (char * nf_packet, struct pkt_struct * pkt)
init the current packet structure with meta-information such as the origin and the number of bytes of data
init_pkt
Parameters:
[in] nf_packet,: The raw packet from the queue
[in] pkt,: The packet metadata structure for this packet
Returns:
the origin of the packet
TODO: check if it's correctly freed
Create fake ethernet header (used later by bpf_filter)
The most important part is to give to this ethernet header the type "IP protocol"
Add the packet IP header and payload to the packet structure
THOMAS:Let's save memory!
Process TCP packets
key_src is the tuple with the source information {Source IP}:{Source Port}
key_dst is the one with the destination information {Dest IP}:{Dest Port}
Process UDP packet
key_src
key_dst
Every other packets are ignored
References pkt_struct::data, pkt_struct::DE, ETHER_HDR_LEN, EXT, packet::FRAME, H, packet::ip, pkt_struct::key, pkt_struct::key_dst, pkt_struct::key_src, NOK, OK, pkt_struct::origin, pkt_struct::packet, packet::payload, pkt_struct::position, pkt_struct::size, packet::tcp, and packet::udp.
char* lookup_honeypot_addr (gchar * testkey, int list)
return the low/high interaction honeypot currently associated with the low/high interaction honeypot in argument
lookup_honeypot_addr
Parameters:
[in] the key of the honeypot, or honeypot+external host, we want to lookup in the redirection table
[in] the list we want to look into, either Low or High
Returns:
The honeypot IP found, NULL if nothing is found
We test which list we want to search
ROBIN 2009-02-25: small hack to include full network definition
get the corresponding hih destination from the low interaction hash table
get the corresponding lih destination from the high interaction hash table
Check first if the high_redirection_table is not null
References H, high_redirection_table, LIH, and low_redirection_table.
char* lookup_origin (int origin)
References EXT, HIH, and LIH.
char* lookup_proto (int proto)
char* lookup_state (int state)
References CONTROL, DECISION, DROP, FORWARD, INIT, INVALID, PROXY, and REPLAY.
Referenced by switch_state().
void print_hex_ascii_line (const u_char * payload, int len, int offset)
Referenced by print_payload().
void print_payload (const u_char * payload, int len)
print_payload
References print_hex_ascii_line().
int setup_redirection (struct conn_struct * conn)
called for each connection being redirected to setup and start the redirection process
setup_redirection
Parameters:
[in] conn,: redirected connection metadata
Returns:
OK when done, NOK in case of failure
we check for concurrent connections using the same EXT_IP:PORT <-> HIH_IP:PORT
conn->key_hih = hihaddr;
We then update the status of the connection structure
We reset the LIH
We replay the first packets
References hih_struct::addr, addr2int(), target::back_handler, conn_struct::BUFFER, DECISION, define_expected_data(), EXT, FORWARD, forward(), H, high_redirection_table, conn_struct::hih, conn_struct::id, conn_struct::key, conn_struct::key_ext, conn_struct::key_lih, hih_struct::lih_addr, NOK, OK, pkt_struct::origin, hih_struct::port, REPLAY, conn_struct::replay_id, reset_lih(), conn_struct::stat_time, switch_state(), and conn_struct::target.
Referenced by DE_process_packet().
int store_pkt (struct conn_struct * conn, struct pkt_struct * pkt)
Store the current packet as part of the connection to replay it later. If this is the first packet of a communication, init its structure in the main B-Tree.
store_pkt function
Parameters:
[in] pkt,: struct pkt_struct to work with
[in] conn,: struct conn_struct to work with
Returns:
the position of the packet in the list in case of success, a negative value if storage has failed
Lock the structure
g_static_rw_lock_writer_lock (&conn->lock);
Append pkt to the singly-linked list of conn
Get the packet position
Unlock the structure
g_static_rw_lock_writer_unlock (&conn->lock);
References conn_struct::BUFFER, H, conn_struct::id, conn_struct::key, OK, and pkt_struct::position.
int switch_state (struct conn_struct * conn, int new_state)
References H, conn_struct::id, lookup_state(), OK, and conn_struct::state.
Referenced by DE_process_packet(), replay(), and setup_redirection().
int test_honeypot_addr (char * key, int list)
compare an IP with a list of honeypot addresses
test_honeypot_addr
Parameters:
[in] the key ip:port of the host we want to test in the list
[in] the list we want to look into, either Low or High
Returns:
0 if the key is found in the list, anything else if not
We extract the IP from the key
small hack to be able to define matching pattern for multiple IP at once
We convert the IP from char to int
We test which list we want to search
if the IP is detected in the list of low honeypot addresses
We then test by increasing the size of the network progressively:
if the IP is detected in the list of high honeypot addresses
References addr2int(), high_honeypot_addr, HIH, LIH, low_honeypot_addr, NOK, and OK.